repos:
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    - id: add-trailing-comma
      name: add-trailing-comma
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
    - id: flake8
      name: flake8
default_language_version:
    python: python3.11
