# Generated by Django 5.0.2 on 2024-02-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', 'title'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', 'title'], 'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
    ]
