# Generated by Django 5.0.2 on 2024-02-14 15:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productincart_shoppingcart_productincart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
